# Markdownlint configuration
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
# Khoguan default: true => false
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters. Khoguan: default is 80
  line_length: 120
  # Number of characters for headings. Khoguan 120 => 80 (default)
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD025/single-title - Multiple top-level headings in the same document
MD025: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:!"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style: 'one' or 'ordered' or 'one_or_ordered' or 'zero'
  style: "one_or_ordered"

# MD004/ul-style - Unordered list style
MD004:
  # List style: 'consistent' or 'asterisk' or 'plus' or 'dash' or 'sublist'
  style: "consistent"

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2
  # Whether to indent the first level of the list
  start_indented: false

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  code_blocks: false
  # Number of spaces for each hard tab
  spaces_per_tab: 2

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 2

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022:
  # Blank lines above heading
  lines_above: 1
  # Blank lines below heading
  lines_below: 1

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031:
  # Include list items
  list_items: true

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036:
  # Punctuation characters
  punctuation: ".,;:!?。，；：！？"

# MD044/proper-names - Proper names should have the correct capitalization
MD044: false

# MD046/code-block-style - Code block style
MD046:
  # Block style: 'consistent' or 'fenced' or 'indented'
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  # Code fence style: 'consistent' or 'backtick' or 'tilde'
  style: "backtick"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  # Emphasis style: 'consistent' or 'asterisk' or 'underscore'
  style: "consistent"

# MD050/strong-style - Strong style should be consistent
MD050:
  # Strong style: 'consistent' or 'asterisk' or 'underscore'
  style: "consistent"
